<?php
include("includes/header02.php");

?>


<!-- begin search sectie  -->
<div class="col-lg col-12 mt-3 mb-3">
    <div class="row mx-0">
        <div class="col-12 card bg-light mx-auto">
            <h1 class="text-center pt-3">Vind <strong>jouw</strong> dier!</h1>
            <p class="text-center">Momenteel zijn er <strong>709</strong> dieren beschikkbaar voor adoptie</p>
            <hr>
            <form class="card-body text-center">
                <div class="form-group row">
                    <label for="location1" class="col-form-label">Kies jouw regio</label>
                    <select class="form-control" name="location" id="location1">
                        <option value="">Alle provincies</option>
                        <option value="">West-Vlaanderen</option>
                        <option value="">Oost-Vlaanderen</option>
                        <option value="">Vlaams Brabant</option>
                    </select>
                </div>
                <div class="form-group row">
                    <label for="location2" class="col-form-label">Kies jouw diersoort</label>
                    <select class="form-control" name="location" id="location2">
                        <option value="">Alle diersoorten</option>
                        <option value="">Honden</option>
                        <option value="">Katten</option>
                        <option value="">Konijnen</option>
                        <option value="">Paarden</option>
                        <option value="">Vogels</option>
                        <option value="">Knaagdieren</option>
                        <option value="">Reptielen</option>
                        <option value="">Andere diersoorten</option>
                    </select>
                </div>
                <p class="text-center"><a href="#" class="btn btn-secondary btn-block" role="button">Search </a></p>
            </form>
        </div>
    </div>
    <!-- end search sectie  -->

    <!-- begin hero carousel -->
    <!-- TO BE AUTO-GENERATED BY PHP  -->
    <!-- <div class="pb-5 container mt-3">
        <div class="row">
            <div class="col-12">
                <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
                    <ol class="carousel-indicators">
                        <li data-target="#carouselExampleControls" data-slide-to="0" class="active"></li>
                        <li data-target="#carouselExampleControls" data-slide-to="1"></li>
                        <li data-target="#carouselExampleControls" data-slide-to="2"></li>
                    </ol>
                    <div class="carousel-inner">
                        <div class="carousel-item active">
                            <img class="d-block w-100" src="http://placeimg.com/1920/500/animals" alt="First slide">
                            <div class="carousel-caption d-none d-md-block">
                                <h5 class="bg-dark text-white">Snowball
                                    <p>Twee jaar oud</p>
                                </h5>
                            </div>
                        </div>
                        <div class="carousel-item">
                            <img class="d-block w-100" src="http://placeimg.com/1920/500/animals" alt="Second slide">
                            <div class="carousel-caption d-none d-md-block">
                                <h5 class="bg-dark text-white">Snowball
                                    <p>Twee jaar oud</p>
                                </h5>
                            </div>
                        </div>
                        <div class="carousel-item">
                            <img class="d-block w-100" src="http://placeimg.com/1920/500/animals" alt="Third slide">
                            <div class="carousel-caption d-none d-md-block">
                                <h5 class="bg-dark text-white">Snowball
                                    <p>Twee jaar oud</p>
                                </h5>
                            </div>
                        </div>
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
            </div>
        </div>
    </div> -->
    <!-- end hero carousel  -->


    <!-- begin recently added sectie  -->
    <!-- TO BE AUTO-GENERATED BY PHP  -->
    <section class="bg-light card mb-3 mt-3">
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-12">
                    <h3 class="pt-3 text-center">
                        Recent toegevoegde dieren
                    </h3>
                    <hr>
                    <div class="row">
                        <div class="col-4">
                            <div class="text-center"> <img src="http://placeimg.com/100/100/animals"
                                    alt="Thumbnail Image 1">
                            </div>
                        </div>
                        <div class="col-4">
                            <div class="text-center"> <img src="http://placeimg.com/100/100/animals"
                                    alt="Thumbnail Image 1">
                            </div>
                        </div>
                        <div class="col-4">
                            <div class="text-center"> <img src="http://placeimg.com/100/100/animals"
                                    alt="Thumbnail Image 1">
                            </div>
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-4">
                            <div class="text-center"> <img src="http://placeimg.com/100/100/animals"
                                    alt="Thumbnail Image 1">
                            </div>
                        </div>
                        <div class="col-4">
                            <div class="text-center"> <img src="http://placeimg.com/100/100/animals"
                                    alt="Thumbnail Image 1">
                            </div>
                        </div>
                        <div class="col-4">
                            <div class="text-center"> <img src="http://placeimg.com/100/100/animals"
                                    alt="Thumbnail Image 1">
                            </div>
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-4">
                            <div class="text-center"> <img src="http://placeimg.com/100/100/animals"
                                    alt="Thumbnail Image 1">
                            </div>
                        </div>
                        <div class="col-4">
                            <div class="text-center"> <img src="http://placeimg.com/100/100/animals"
                                    alt="Thumbnail Image 1">
                            </div>
                        </div>
                        <div class="col-4">
                            <div class="text-center"> <img src="http://placeimg.com/100/100/animals"
                                    alt="Thumbnail Image 1">
                            </div>
                        </div>
                    </div>
                </div>
                <!-- end recently added sectie -->


                <!-- begin dieren info - tabs  -->
                <div class="col-md-6 col-12">
                    <h3 class="pt-3 text-center">
                        Zorgen voor huisdieren
                    </h3>
                    <nav>
                        <div class="nav nav-tabs" id="nav-tab" role="tablist">
                            <a class="nav-item nav-link active" id="nav-home-tab" data-toggle="tab" href="#nav-home"
                                role="tab" aria-controls="nav-home" aria-selected="true">Honden</a>
                            <a class="nav-item nav-link" id="nav-katten-tab" data-toggle="tab" href="#nav-katten"
                                role="tab" aria-controls="nav-katten" aria-selected="false">Katten</a>
                            <a class="nav-item nav-link" id="nav-konijnen-tab" data-toggle="tab" href="#nav-konijnen"
                                role="tab" aria-controls="nav-konijnen" aria-selected="false">Konijnen</a>
                            <a class="nav-item nav-link" id="nav-kippen-tab" data-toggle="tab" href="#nav-kippen"
                                role="tab" aria-controls="nav-kippen" aria-selected="false">Kippen</a>
                            <a class="nav-item nav-link" id="nav-paarden-tab" data-toggle="tab" href="#nav-paarden"
                                role="tab" aria-controls="nav-paarden" aria-selected="false">Paarden</a>
                        </div>
                    </nav>
                    <div class="tab-content" id="nav-tabContent">
                        <div class="tab-pane fade show active" id="nav-home" role="tabpanel"
                            aria-labelledby="nav-home-tab">
                            <p>
                            <ul>
                                <li>Heb je de ruimte en de tijd om een hond dagelijks vrij buiten te laten bewegen?</li>
                                <li>Ga je graag wandelen, ook als het regent of koud is?</li>
                                <li>Wil je dagelijks de uitwerpselen opruimen en/of de hond zindelijk maken?</li>
                                <li>Ben je bereid om per maand 85 euro kosten (per jaar 700 - 1300 euro) te betalen ?
                                </li>
                                <li>Wil je de komende 10 – 20 jaar voor de hond zorgen?</li>
                                <li>Heb je een oplossing voor de hond als je op vakantie gaat of een lange dag weg ben?
                                </li>
                                <li>Kan je er tegen dat de hond veel vuil maakt of soms iets stuk maakt?</li>
                                <li>Heb je genoeg ruimte binnen en/of is de tuin hoog genoeg omhend?</li>
                            </ul>
                            Als je op één van deze vragen nee antwoordt, dan is de adoptie van een hond misschien toch
                            geen goed idee.
                            </p>

                        </div>
                        <div class="tab-pane fade" id="nav-katten" role="tabpanel" aria-labelledby="nav-katten-tab">
                            <p>
                                Voorkom probleemgedrag en schade aan de meubels door je huis katvriendelijk in te
                                richten. Van alle benodigdheden heb je er één meer nodig dan het aantal katten in huis.
                                Voor één kat zijn er dus twee kattenbakken nodig, voor twee katten drie kattenbakken
                                enzovoort.
                            <p>
                                Zet alle kattenspullen verspreid in huis neer. Zet bijvoorbeeld niet alle kattenbakken
                                bij elkaar in de berging. Zo voorkom je dat één kat de toegang naar de kattenbakken voor
                                de andere katten kan blokkeren door voor de deur te gaan zitten.
                            </p>
                            Het voer en het drinken mogen niet in de buurt van de kattenbak staan. Dit kan er toe leiden
                            dat de kat zijn behoefte op ongewenste plaatsen in huis doet. Zorg ook dat het voer en het
                            drinken niet naast mekaar staan: laat er minstens 1,5 meter tussen. Katten houden er niet
                            van om te drinken in de buurt van hun eten. Daardoor drinken ze soms te weinig, wat de kans
                            op blaasproblemen verhoogt.
                            </p>
                        </div>
                        <div class="tab-pane fade" id="nav-konijnen" role="tabpanel" aria-labelledby="nav-konijnen-tab">
                            <p>
                                In tegenstelling tot wat vaak wordt gedacht, zijn konijnen <strong> geen goede
                                    huisdieren voor kinderen</strong>. De meeste konijnen vinden oppakken en knuffelen
                                niet leuk. Ze kunnen dan krabben en bijten en <em> zelfs hun eigen rug breken</em> als
                                ze spartelen bij het optillen.
                            <p>
                                Door veel tijd aan het konijn te besteden en er rustig mee om te gaan, kan het wel tam
                                worden en leren dat aaien prettig kan zijn. Konijnen kunnen ook allerlei trucjes leren
                                en er wordt zelfs aan konijnen-agility gedaan. <em> Konijnen zijn dus vooral leuke
                                    huisdieren voor mensen die er ofwel veel mee willen bezig zijn, ofwel er vooral
                                    willen naar kijken.</em></p>
                            </p>
                            <p>
                                Konijnen hebben veel ruimte nodig. Combineer een hok of kooi met een grote (buiten)ren
                                en richt deze in met veel verstopplekjes en verschillende niveaus.
                            </p>
                            <p>
                                Een konijn is een groepsdier. <strong> Hou er minstens twee</strong>. De combinatie van
                                een vrouwelijk konijn en een gecastreerd mannelijk konijn gaat het best. Twee mannetjes
                                of twee vrouwtjes samen geeft meestal ruzie.
                            </p>
                        </div>
                        <div class="tab-pane fade" id="nav-kippen" role="tabpanel" aria-labelledby="nav-kippen-tab">
                            <p>
                                Kippen bestaan in veel maten, kleuren en temperamenten. Er zijn rassen die vooral
                                geschikt zijn om veel eieren te leggen en andere worden vooral gehouden voor het vlees
                                of voor de sierwaarde. Naast echte raskippen worden er ook veel kruisingen gekweekt, de
                                hybriden. Deze hybriden geven een veel grotere opbrengst van eieren of vlees dan de
                                zuivere rassen en worden daarom veel in de industrie gebruikt. Ook de meeste legkippen
                                die je in de dierenwinkel kan kopen, zijn hybriden. Ze leven doorgaans echter minder
                                lang en zijn minder sterk dan de zuivere raskippen.
                            </p>
                            <p>
                                Om de kippen te vervoeren, kan je een speciaal kippenkrat gebruiken of een stevige
                                kartonnen doos met luchtgaten. Zo kunnen de kippen veilig en rustig vervoerd worden. Zet
                                de doos goed vast in de auto, zodat deze niet aan het schuiven gaat. Kippen geraken snel
                                oververhit. Transporteer ze dus niet op warme dagen en zorg voor voldoende ventilatie.
                            </p>
                            <p>
                                Richt het hok en de ren in voordat je de kippen koopt. Zet de kippen bij aankomst in het
                                binnenhok en laat hen zelf de weg naar buiten ontdekken. Geef in het begin hetzelfde
                                voer als de vorige eigenaar en wen ze geleidelijk aan nieuw voer.
                            </p>
                        </div>
                        <div class="tab-pane fade" id="nav-paarden" role="tabpanel" aria-labelledby="nav-paarden-tab">
                            <p>
                                Paarden zijn kuddedieren die bij voorkeur in een kleine kudde leven. Andere dieren,
                                zoals geiten of ezels, kunnen ook op dezelfde weide staan, maar ze vervangen het
                                gezelschap van een ander paard niet.</p>
                            <p>
                                Als je zelf maar één paard kan houden, zorg er dan voor dat het dier andere paarden kan
                                zien of probeer met andere paardeneigenaars af te spreken om de dieren samen te zetten.
                            </p>
                            <p>
                                Als je een nieuw paard in de groep brengt, dan hou je het eerst een aantal weken apart
                                in een aangrenzende weide. Zo leren de dieren elkaar eerst kennen zonder dat ze een
                                bedreiging vormen voor elkaar. Als de dieren gezond zijn en ze elkaar goed kennen en
                                verdragen, dan kan je ze voor het eerst samen zetten. Voorkom agressie over voeder door
                                op meerdere plaatsen hooi en water aan te bieden.
                            </p>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    </div>
    <!-- end dieren info - tabs  -->


<?php
include("includes/footer.php");
?>